name: Release Chart

on:
  push:
    tags:
      - '*'
jobs:
  release_helm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v6.0.2

      - run: helm package --dependency-update .
      - run: helm registry login ghcr.io --username ${{ github.repository_owner }} --password ${{ github.token }}
      - run: helm push -- *.tgz "oci://ghcr.io/${GITHUB_REPOSITORY}"
